export { default as Login } from './Login'
export { default as CreateAccount } from './CreateAccount'
export { default as Home } from './Home'
export { default as ListaTelefones } from './ListaTelefones'
export { VerificarPedidosParados, ConsultarPedidos, ResultadosConsulta, Evolucao } from './VerificarPedidosParados'
export { default as SLA } from './SLA'
export { default as SLAPerformance } from './SLA/SLAPerformance'
export { default as Analise } from './SLA/Analise'
export { default as Profile } from './Profile'
export { default as Documentacao } from './Documentacao/Documentacao'